### ISSUE TITLE
Dataplane API Unable to rename haproxy.cfg when trying to commit transaction

### ISSUE THREAD

**Issue by penghongkwek** [haproxytech/haproxy-docker-ubuntu#3]
I executed this following URL to commit the transaction

curl -X PUT --user admin:mypassword \
       -H "Content-Type: application/json" \
       http://localhost:5555/v2/services/haproxy/transactions/{transaction_id}

Result
------
{"code":500,"message":"rename /tmp/.haproxy.cfg038157959 /usr/local/etc/haproxy/haproxy.cfg: device or resource busy"}

docker-compose.yml
-----------------------
haproxy:
  image: haproxytech/haproxy-ubuntu:latest
  volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:rw
  ports:
    - 8080:80
    - 5555:5555

Please advise. Thank you

**Comment by dkorunic** [comment]
@penghongkwek Exposing a single file as a volume for a HAProxy configuration can't work as Dataplane uses atomic I/O to rename temporary configuration to haproxy.cfg which would overwrite a volume. Make sure to always use regular directory as /usr/local/etc/haproxy and not a single file.

**Comment by Rezkmike** [comment]
@penghongkwek , does it really work when you changed the volume mount from file to directory? could you share your solution. thanks
