### ISSUE TITLE
get Missing LF on last line error always

### ISSUE THREAD

**Issue by ZebcoWeb** [haproxytech/haproxy-docker-ubuntu#4]
when i want run with docker-compose i get this error always:

`haproxy-service | [NOTICE]   (1) : haproxy version is 2.4.7-b5e51a5
haproxy-service | [ALERT]    (1) : parsing [/usr/local/etc/haproxy/haproxy.cfg:26]: Missing LF on last line, file might have been truncated at position 28.
haproxy-service | [ALERT]    (1) : Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
haproxy-service | [ALERT]    (1) : Fatal errors found in configuration.`

**OS:** windows 11
**docker-version:** Docker version 20.10.8, build 3967b7d

**Comment by dkorunic** [comment]
@ZebcoWeb You need to create a proper HAProxy configuration file and expose it in Docker container under /usr/local/etc/haproxy file, for instance like [this](https://github.com/haproxytech/haproxy-docker-ubuntu#use-volume-for-configuration-persistency). It doesn't matter if it's being done through Docker Compose or with Docker directly, underlying volume happens in the same way. In both these cases configuration file should be valid.

**Comment by wenqiangde** [comment]
add space at last line.

**Comment by wenqiangde** [comment]
new line at last line.
