### ISSUE TITLE
Help me example bind *443

### ISSUE THREAD

**Issue by hoaiphong0958** [haproxytech/haproxy-docker-ubuntu#5]
Anyone can help me a full example config about this version

**Comment by dkorunic** [comment]
Dear @hoaiphong0958, there are many articles and blog posts related to this subject, for instance: https://www.haproxy.com/blog/haproxy-ssl-termination/. Minimal example would be:

```
frontend myfrontend
  bind :80
  bind :443 ssl crt /usr/local/etc/haproxy/certs/mycert.pem
 ```
