### ISSUE TITLE
Use jemalloc instead of glibc

### ISSUE THREAD

**Issue by bfelbo** [haproxytech/haproxy-docker-ubuntu#7]
@wtarreau has mentioned that jemalloc is "both significantly faster and less memory hungry than the default one from glibc" and that it's the choice for the ALOHA appliances, which are doing load balancing at scale.

Have you considering switching the Docker images to use jemalloc or adding another Docker image with jemalloc?

**Comment by dkorunic** [comment]
We will discuss this internally first, but have in mind that Docker HAProxy containers are in general less frequently used for such large scale of traffic where differences between GNU allocator vs jemalloc (or any other) are visible enough.

**Comment by bfelbo** [comment]
Makes sense. Besides performance improvements, the other benefit of using jemalloc would be stability.

We're seeing some `ha_panic` and memory segmentation errors during blue-green deployment. It'd be useful if the Docker image used the recommended memory allocation approach so we can rule that out as one of the potential issues. Similarly, it might help avoid issues like https://github.com/haproxy/haproxy/issues/1782, which were resolved by switching to jemalloc.

**Comment by dkorunic** [comment]
Adding jemalloc is in progress for 2.4-2.9 branches for Debian, Ubuntu and Alpine images; I'll close this issue once this has been completed.

**Comment by bfelbo** [comment]
Amazing, thanks 🙌

**Comment by dkorunic** [comment]
Done. Let me know if you spot any issues.
